site_name: Health & Fitness
site_author: Sanket Naik
nav:
 - 'BASICS OF FOOD AND NUTRITION':
   - 'Introduction to Health And Nutrition': 'index.md'
   - 'Obesity And Lifestyle Disorders': 'chapter-2.md'
   - 'Nutrition Pyramid': 'chapter-3.md'
   - 'Calories and Energy Balance': 'chapter-4.md'
   - 'Introduction to Macronutrients': 'chapter-5.md'
   - 'Introduction to Micronutrients': 'chapter-6.md'
   - 'Introduction to Quantified Nutrition': 'chapter-7.md'
   - 'Food Relationship and Your Health': 'chapter-8.md'
 - 'INTRODUCTION TO EXERCISE SCIENCE':
    - 'Types Of Exercise': 'chapter-9.md'
    - 'Importance Of Exercise': 'chapter-10.md'
    - 'Basic Components Of Fitness': 'chapter-11.md'
    - 'Types Of Exercises': 'chapter-12.md'
    - 'Exercise Planning And Building Routine': 'chapter-13.md'
    - 'Impact Of Exercise On Lifestyle Disorders': 'chapter-14.md'
    - 'Exercise For General Population': 'chapter-15.md'
 - 'INTRODUCTION TO RESISTANCE TRAINING':
    - 'What Is Resistance Training ?': 'chapter-16.md'
    - 'Introduction To Basic Muscle Groups': 'chapter-17.md'
    - 'Introduction To Training Variables and their Importance': 'chapter-18.md'
    - 'Basics of Exercise Planning': 'chapter-19.md'
    - 'Tracking and Progression': 'chapter-20.md'
 - 'BASICS OF ANATOMY AND PHYSIOLOGY':
    - 'Plane Of Motion': 'chapter-21.md'
    - 'Muscular System': 'chapter-22.md'
    - 'Sliding Filament Theory': 'chapter-23.md'
    - 'Skeletal System' : 'chapter-24.md'
    - 'The Cardiovascular and Nervous System' : 'chapter-25.md'
    - 'Endocrine System': 'chapter-26.md'
    - 'Exercise Physiology': 'chapter-27.md'
 - 'INTRODUCTION TO THE GYM':
    - 'Fitness Testing': 'chapter13.md'
    - 'Health Parameters': 'chapter14.md'
    - 'Client Assessment': 'chapter15.md'
    - 'Goal Setting': 'chapter16.md'
    - 'Program Implementation': 'chapter17.md'
    - 'Exercise Sessions': 'chapter18.md'


theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.collapse    # This enables the accordion/dropdown effect
    - navigation.tracking    # This keeps the active link in view
    - navigation.path      # This shows the breadcrumbs at the top
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css
